import Link from 'next/link';
import Image from 'next/image';
import { 
  Scale, 
  ShieldAlert, 
  ArrowLeft, 
  Terminal 
} from 'lucide-react';

export const metadata = {
  title: 'Terms of Use — INDRA Sovereign AI Workbench',
  description: 'Statutory engineering terms of use, deterministic calculation disclaimers, and human-in-the-loop sign-off governance.',
};

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-100 flex flex-col font-sans selection:bg-emerald-500 selection:text-white dark:selection:text-slate-950 transition-colors">
      {/* Header */}
      <header className="border-b border-slate-200 dark:border-slate-800 bg-white/90 dark:bg-slate-950/90 backdrop-blur sticky top-0 z-50 transition-colors">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href="/" className="flex items-center gap-3 group">
              <div className="relative w-8 h-8 rounded-lg overflow-hidden border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 flex-shrink-0">
                <Image src="/logo.png" alt="INDRA" fill className="object-contain p-1" />
              </div>
              <div>
                <div className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-emerald-500 transition-colors">
                  INDRA
                </div>
                <div className="text-[10px] font-mono text-slate-500 dark:text-slate-400">STATUTORY USAGE TERMS</div>
              </div>
            </Link>
          </div>

          <div className="flex items-center gap-3">
            <Link
              href="/"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white hover:bg-slate-100 dark:bg-slate-900 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-300 dark:border-slate-700 text-xs font-mono transition-colors shadow-2xs"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>Back to Home</span>
            </Link>
            <Link
              href="/workbench"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-mono font-semibold transition-colors shadow-xs"
            >
              <span>Launch Workbench</span>
            </Link>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-12 flex-1">
        <div className="space-y-8">
          {/* Header Banner */}
          <div className="border-b border-slate-200 dark:border-slate-800 pb-8">
            <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-md bg-amber-50 dark:bg-amber-950/60 border border-amber-200 dark:border-amber-800/80 text-amber-700 dark:text-amber-400 text-xs font-mono mb-4">
              <Scale className="w-3.5 h-3.5" />
              <span>STATUTORY ENGINEERING GOVERNANCE</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
              Terms &amp; Conditions of Industrial Use
            </h1>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-2 font-mono">
              Effective Date: September 2026 &bull; Scope: Petrochemical, Refinery &amp; Heavy Process Deployments
            </p>
          </div>

          {/* Statutory Advisory Notice Callout */}
          <div className="p-4 rounded-lg bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800/60 text-amber-900 dark:text-amber-200 text-xs space-y-2">
            <div className="flex items-center gap-2 font-bold text-amber-800 dark:text-amber-300 text-sm font-mono">
              <ShieldAlert className="w-4 h-4 text-amber-600 dark:text-amber-400 flex-shrink-0" />
              <span>CRITICAL STATUTORY ENGINEERING NOTICE (ASME B31.3 / API 570)</span>
            </div>
            <p className="leading-relaxed text-slate-700 dark:text-amber-200/90">
              INDRA is an advanced engineering computational assistant and decision-support tool. All calculations, wall thickness assessments, vibration severity scores, and statutory approval notes generated by INDRA are advisory and must be reviewed, stamped, or signed off by a certified <strong>Professional Engineer (PE)</strong>, <strong>API 570 Certified Inspector</strong>, or statutory <strong>Plant Superintendent</strong> prior to physical plant alterations or operating envelope changes.
            </p>
          </div>

          {/* Detailed Terms Sections */}
          <div className="space-y-8 text-sm text-slate-600 dark:text-slate-300 leading-relaxed font-sans">
            <section className="space-y-3">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2 font-mono">
                <span className="text-amber-600 dark:text-amber-400">01.</span>
                <span>Deterministic Calculation Scope &amp; Boundaries</span>
              </h2>
              <p>
                Calculations performed by INDRA execute via deterministic Python numerical solvers implementing standardized mathematical equations:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-slate-500 dark:text-slate-400">
                <li><strong className="text-slate-800 dark:text-slate-200">ASME B31.3 Section 304.1.2:</strong> Straight pipe minimum required wall thickness based on internal design pressure, allowable stress, joint quality factor, and temperature coefficient.</li>
                <li><strong className="text-slate-800 dark:text-slate-200">API 570 Section 7.1.1:</strong> Remaining life and statutory inspection intervals based on measured thickness, nominal thickness, and linear corrosion rate.</li>
                <li><strong className="text-slate-800 dark:text-slate-200">ISO 10816-3:</strong> Vibration velocity RMS harmonic evaluation for rotating machinery.</li>
              </ul>
              <p>
                The operator is solely responsible for ensuring that all physical telemetry, material grades (e.g. ASTM A106 Gr. B vs. 316L SS), design pressures, and operating temperatures inputted into the system accurately reflect real-world plant conditions.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2 font-mono">
                <span className="text-amber-600 dark:text-amber-400">02.</span>
                <span>Human-in-the-Loop (HITL) Gate Responsibilities</span>
              </h2>
              <p>
                Under no circumstances does INDRA transmit unverified setpoints directly to programmable logic controllers (PLCs), distributed control systems (DCS), or emergency shutdown systems (ESD) without explicit human confirmation.
              </p>
              <p>
                Any parameter modification, motor RPM adjustment, or valve override must be authorized via the 3-Tier Human-in-the-Loop approval modal. The operator or supervisor submitting their cryptographic name/signature in the HITL interface assumes legal and statutory operational custody of that action.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2 font-mono">
                <span className="text-amber-600 dark:text-amber-400">03.</span>
                <span>On-Premise Software Licensing &amp; Sovereignty</span>
              </h2>
              <p>
                INDRA is provided for deployment within authorized on-premise industrial environments. The enterprise licensee retains complete ownership of:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-slate-500 dark:text-slate-400">
                <li>All proprietary P&amp;ID schematics, CAD files, and engineering drawings uploaded to the system.</li>
                <li>All ultrasonic thickness survey reports, NDT non-destructive testing logs, and telemetry feeds.</li>
                <li>All generated deliverables (.docx statutory notes, .xlsx calculation sheets, .pptx board review decks).</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2 font-mono">
                <span className="text-amber-600 dark:text-amber-400">04.</span>
                <span>Limitation of Liability in Operational Plants</span>
              </h2>
              <p>
                In no event shall the authors, maintainers, or contributors of INDRA be held liable for mechanical failures, pressure vessel ruptures, loss of containment, unplanned refinery outages, or consequential damages resulting from improper operating parameters, undetected metallurgical fatigue, unverified AI outputs, or failure to follow statutory plant operating procedures (SOPs).
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2 font-mono">
                <span className="text-amber-600 dark:text-amber-400">05.</span>
                <span>Cryptographic Audit Trail Integrity</span>
              </h2>
              <p>
                The Merkle audit ledger provides cryptographic proof of data immutability. Tampering with local audit blocks, falsifying sign-off identities, or modifying historical records constitutes a breach of operational integrity protocols and statutory compliance requirements.
              </p>
            </section>
          </div>

          {/* Action Footer */}
          <div className="pt-8 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between">
            <Link
              href="/privacy"
              className="text-xs font-mono text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
            >
              &larr; Review Privacy Policy
            </Link>
            <Link
              href="/workbench"
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-mono font-semibold transition-colors shadow-xs"
            >
              <Terminal className="w-3.5 h-3.5" />
              <span>Proceed to Workbench</span>
            </Link>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 py-6 text-xs text-slate-500 font-mono transition-colors">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 flex items-center justify-between">
          <span>INDRA Sovereign AI &bull; Air-Gapped Workstation Distribution</span>
          <div className="flex items-center gap-4">
            <Link href="/" className="hover:text-slate-900 dark:hover:text-slate-300">Home</Link>
            <Link href="/privacy" className="hover:text-slate-900 dark:hover:text-slate-300">Privacy</Link>
            <Link href="/workbench" className="hover:text-slate-900 dark:hover:text-slate-300">Workbench</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
