/**
 * Equipment Catalog & Engineering Specifications
 * 
 * Complies with ANSI/ISA-5.1 Instrumentation Symbols and Identification
 * and ASME Y14.1 / ISO 5457 drawing format standards.
 */

export type EquipmentCategory =
  | 'pumps'
  | 'exchangers'
  | 'columns'
  | 'valves'
  | 'compressors'
  | 'tanks'
  | 'inline';

export interface EquipmentPort {
  id: string;
  type: 'inlet' | 'outlet' | 'vent' | 'drain';
  label: string;
  position: 'top' | 'bottom' | 'left' | 'right';
}

export interface EquipmentAsset {
  id: string;
  tag: string;
  name: string;
  category: EquipmentCategory;
  standard: string;
  subType: string;
  specs: { label: string; value: string }[];
  ports: EquipmentPort[];
  color: string;
  symbol: string; // Identifier for SVG symbol rendering
}

export interface LineSpec {
  id: string;
  label: string;
  size: string;
  service: string;
  serviceCode: string;
  materialClass: string;
  color: string;
  description: string;
}

export interface AnsiPaperFormat {
  id: 'A0' | 'A1' | 'A2' | 'A3' | 'A4' | 'NONE';
  name: string;
  label: string;
  width: number;
  height: number;
  mmWidth: number;
  mmHeight: number;
  zonesX: number;
  zonesY: number;
}

export const ANSI_PAPER_FORMATS: Record<'A0' | 'A1' | 'A2' | 'A3' | 'A4' | 'NONE', AnsiPaperFormat> = {
  A0: {
    id: 'A0',
    name: 'ANSI / ISO A0',
    label: 'A0 (1189 x 841 mm) - Major Plant Master Sheet',
    width: 2378,
    height: 1682,
    mmWidth: 1189,
    mmHeight: 841,
    zonesX: 8,
    zonesY: 6,
  },
  A1: {
    id: 'A1',
    name: 'ANSI / ISO A1',
    label: 'A1 (841 × 594 mm) - Standard Process Unit P&ID',
    width: 1682,
    height: 1188,
    mmWidth: 841,
    mmHeight: 594,
    zonesX: 8,
    zonesY: 6,
  },
  A2: {
    id: 'A2',
    name: 'ANSI / ISO A2',
    label: 'A2 (594 × 420 mm) - Package Unit Schematic',
    width: 1188,
    height: 840,
    mmWidth: 594,
    mmHeight: 420,
    zonesX: 6,
    zonesY: 4,
  },
  A3: {
    id: 'A3',
    name: 'ANSI / ISO A3',
    label: 'A3 (420 × 297 mm) - Sub-System Skid Flowsheet',
    width: 840,
    height: 594,
    mmWidth: 420,
    mmHeight: 297,
    zonesX: 6,
    zonesY: 4,
  },
  A4: {
    id: 'A4',
    name: 'ANSI / ISO A4',
    label: 'A4 (297 × 210 mm) - Single Loop Instrument Diagram',
    width: 594,
    height: 420,
    mmWidth: 297,
    mmHeight: 210,
    zonesX: 4,
    zonesY: 4,
  },
  NONE: {
    id: 'NONE',
    name: 'Infinite Drafting',
    label: 'Infinite Unconstrained Drafting Canvas',
    width: 0,
    height: 0,
    mmWidth: 0,
    mmHeight: 0,
    zonesX: 0,
    zonesY: 0,
  },
};

export const PIPING_LINE_SPECS: LineSpec[] = [
  {
    id: 'spec-p-16',
    label: '16"-P-101-A1A',
    size: '16"',
    service: 'process stream Hydrocarbon Process Feed',
    serviceCode: 'P',
    materialClass: 'CS 150# (A106-B)',
    color: '#10b981', // emerald
    description: 'process stream suction/discharge process transfer line',
  },
  {
    id: 'spec-p-12',
    label: '12"-P-102-A1A',
    size: '12"',
    service: 'Pre-Heated Process Liquid',
    serviceCode: 'P',
    materialClass: 'CS 150# (A106-B)',
    color: '#10b981',
    description: 'Exchanger train intermediate process loop',
  },
  {
    id: 'spec-hc-16',
    label: '16"-HC-201-B3B',
    size: '16"',
    service: 'High-Temperature Hydrocarbon',
    serviceCode: 'HC',
    materialClass: 'Alloy 300# (P11/P22)',
    color: '#f59e0b', // amber
    description: 'Fired heater transfer line to fractionation column',
  },
  {
    id: 'spec-hc-20',
    label: '20"-HC-202-B3B',
    size: '20"',
    service: 'Overhead Vapor Stream',
    serviceCode: 'HC',
    materialClass: 'CS 300# (A106-B)',
    color: '#f59e0b',
    description: 'Column overhead vapor line to condenser',
  },
  {
    id: 'spec-cw-12',
    label: '12"-CW-105-C1A',
    size: '12"',
    service: 'Cooling Water Supply / Return',
    serviceCode: 'CW',
    materialClass: 'Carbon Steel / Internally Coated 150#',
    color: '#06b6d4', // cyan
    description: 'Utility closed-circuit cooling water header',
  },
  {
    id: 'spec-s-06',
    label: '6"-S-301-B1A',
    size: '6"',
    service: 'Medium Pressure Superheated Steam',
    serviceCode: 'S',
    materialClass: 'Cr-Mo Steel 300# (A335-P11)',
    color: '#06b6d4', // cyan
    description: 'Utility stripping steam injection line',
  },
  {
    id: 'spec-bd-04',
    label: '4"-BD-201-D2A',
    size: '4"',
    service: 'Emergency Cryogenic Blowdown',
    serviceCode: 'BD',
    materialClass: 'LTCS 600# (A333-Gr6)',
    color: '#f43f5e', // rose
    description: 'API 521 automated depressuring flare header',
  },
  {
    id: 'spec-ia-02',
    label: '2"-IA-010-A1A',
    size: '2"',
    service: 'Pneumatic Instrument Air',
    serviceCode: 'IA',
    materialClass: 'Galvanized CS 150#',
    color: '#38bdf8', // sky blue
    description: 'Dry instrument air supply to control valves',
  },
];

export const REGISTERED_EQUIPMENT_CATALOG: EquipmentAsset[] = [
  // ----------------------------------------------------
  // 1. PUMPS & DRIVERS (10 items)
  // ----------------------------------------------------
  {
    id: 'asset-pump-01',
    tag: 'P-101A',
    name: 'Centrifugal Process Pump (Single-Stage)',
    category: 'pumps',
    standard: 'API 610 OH2 / ISO 13709',
    subType: 'Overhung End-Suction Process Pump',
    specs: [
      { label: 'Flow Rate', value: '450 m³/h' },
      { label: 'Head', value: '115 m' },
      { label: 'Power', value: '185 kW' },
      { label: 'NPSHa', value: '4.8 m' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction Flange', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge Flange', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Casing Vent', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Casing Drain', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-centrifugal',
  },
  {
    id: 'asset-pump-02',
    tag: 'P-101B',
    name: 'Centrifugal Process Pump (Standby)',
    category: 'pumps',
    standard: 'API 610 OH2 / ISO 13709',
    subType: 'Overhung End-Suction Standby Pump',
    specs: [
      { label: 'Flow Rate', value: '450 m³/h' },
      { label: 'Head', value: '115 m' },
      { label: 'Power', value: '185 kW' },
      { label: 'Status', value: 'AUTO-STANDBY' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Vent', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Drain', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-centrifugal',
  },
  {
    id: 'asset-pump-03',
    tag: 'P-102',
    name: 'Multi-Stage High-Pressure Boiler Feed Pump',
    category: 'pumps',
    standard: 'API 610 BB3 / ISO 13709',
    subType: 'Between-Bearings Axially Split Pump',
    specs: [
      { label: 'Flow Rate', value: '320 m³/h' },
      { label: 'Head', value: '820 m' },
      { label: 'Pressure', value: '85 bar' },
      { label: 'Speed', value: '2,980 RPM' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Recirculation', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Drain', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-multistage',
  },
  {
    id: 'asset-pump-04',
    tag: 'P-103',
    name: 'Positive Displacement Rotary Gear Pump',
    category: 'pumps',
    standard: 'API 676 / ISO 14847',
    subType: 'External Timing Gear Pump',
    specs: [
      { label: 'Flow Rate', value: '38 m³/h' },
      { label: 'Viscosity', value: '450 cSt' },
      { label: 'Delta P', value: '16.5 bar' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Relief', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Drain', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-gear',
  },
  {
    id: 'asset-pump-05',
    tag: 'P-104',
    name: 'Triplex Reciprocating Plunger Pump',
    category: 'pumps',
    standard: 'API 674 / ISO 13710',
    subType: 'High Pressure Plunger Metering',
    specs: [
      { label: 'Flow Rate', value: '14.2 m³/h' },
      { label: 'Pressure', value: '145 bar' },
      { label: 'Strokes', value: '280 SPM' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Damper', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Drain', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-reciprocating',
  },
  {
    id: 'asset-pump-06',
    tag: 'P-105',
    name: 'Diaphragm Chemical Injection Pump',
    category: 'pumps',
    standard: 'API 675 / ISO 19880',
    subType: 'Hydraulically Actuated Diaphragm',
    specs: [
      { label: 'Dosing Flow', value: '120 L/h' },
      { label: 'Accuracy', value: '±1.0%' },
      { label: 'Chemical', value: 'Corrosion Inhibitor' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Chemical Feed', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Injection Quill', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Prime Port', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Flush', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-diaphragm',
  },
  {
    id: 'asset-pump-07',
    tag: 'P-106',
    name: 'Vertical Submersible Sump Pump',
    category: 'pumps',
    standard: 'API 610 VS4 / ISO 13709',
    subType: 'Vertically Suspended Sump Pump',
    specs: [
      { label: 'Column Depth', value: '4.5 m' },
      { label: 'Flow Rate', value: '95 m³/h' },
      { label: 'Solids Limit', value: '25 mm' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction Strainer', position: 'bottom' },
      { id: 'outlet', type: 'outlet', label: 'Discharge Riser', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Level Sensor', position: 'top' },
    ],
    color: '#10b981',
    symbol: 'pump-submersible',
  },
  {
    id: 'asset-pump-08',
    tag: 'P-107',
    name: 'Heavy-Duty Slurry Centrifugal Pump',
    category: 'pumps',
    standard: 'ANSI / HI 12.1-12.6',
    subType: 'Hard-Metal Lined Slurry Unit',
    specs: [
      { label: 'Slurry Conc.', value: '38 wt%' },
      { label: 'Impeller', value: 'High Chrome Alloy' },
      { label: 'Flow Rate', value: '260 m³/h' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Flush Drain', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-centrifugal',
  },
  {
    id: 'asset-pump-09',
    tag: 'P-108',
    name: 'Progressive Cavity Screw Pump',
    category: 'pumps',
    standard: 'API 676 Type 3',
    subType: 'Single Helical Rotor-Stator Pump',
    specs: [
      { label: 'Shear-Sensitive', value: 'True' },
      { label: 'Viscosity Limit', value: '25,000 cSt' },
      { label: 'Speed', value: '320 RPM' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Cleanout', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-screw',
  },
  {
    id: 'asset-pump-10',
    tag: 'P-109',
    name: 'Liquid Ring Vacuum Seal Pump',
    category: 'pumps',
    standard: 'API 681 / ISO 16330',
    subType: 'Water-Sealed Vacuum Package',
    specs: [
      { label: 'Suction Press.', value: '35 mbar a' },
      { label: 'Capacity', value: '1,450 m³/h' },
      { label: 'Seal Fluid', value: 'Water (15°C)' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Vapor Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Separator Vent', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Seal Makeup', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Effluent Drain', position: 'bottom' },
    ],
    color: '#10b981',
    symbol: 'pump-vacuum',
  },

  // ----------------------------------------------------
  // 2. HEAT EXCHANGERS & FIRED HEATERS (10 items)
  // ----------------------------------------------------
  {
    id: 'asset-hx-01',
    tag: 'E-201',
    name: 'Shell & Tube Exchanger (1-Pass Fixed)',
    category: 'exchangers',
    standard: 'TEMA Type BEM / ASME Sec VIII',
    subType: 'Fixed Tubesheet Heat Exchanger',
    specs: [
      { label: 'Heat Duty', value: '14.8 MW' },
      { label: 'Area', value: '1,240 m²' },
      { label: 'Shell Design', value: '28 bar / 240°C' },
      { label: 'Tube Design', value: '45 bar / 180°C' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Tube Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Tube Outlet', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Shell Outlet', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Shell Inlet', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'hx-shell-tube',
  },
  {
    id: 'asset-hx-02',
    tag: 'E-202',
    name: 'Shell & Tube Exchanger (2-Pass Floating Head)',
    category: 'exchangers',
    standard: 'TEMA Type AES / ASME Sec VIII',
    subType: 'Removable Floating Head Exchanger',
    specs: [
      { label: 'Heat Duty', value: '21.5 MW' },
      { label: 'Area', value: '1,890 m²' },
      { label: 'Thermal Delta', value: '42.5°C' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Tube In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Tube Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Shell Out', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Shell In', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'hx-shell-tube',
  },
  {
    id: 'asset-hx-03',
    tag: 'E-203',
    name: 'Plate & Frame Compact Heat Exchanger',
    category: 'exchangers',
    standard: 'API 662-1 / ISO 15547-1',
    subType: 'Gasketed PHE (Titanium Plates)',
    specs: [
      { label: 'Heat Duty', value: '8.4 MW' },
      { label: 'Plate Material', value: 'Ti Grade 2' },
      { label: 'Approach Temp', value: '2.5°C' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Hot Stream In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Hot Stream Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Cold Out', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Cold In', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'hx-plate',
  },
  {
    id: 'asset-hx-04',
    tag: 'E-204',
    name: 'Air-Cooled Fin-Fan Heat Exchanger',
    category: 'exchangers',
    standard: 'API 661 / ISO 13706',
    subType: 'Induced Draft Aerial Cooler',
    specs: [
      { label: 'Cooling Duty', value: '18.2 MW' },
      { label: 'Fans', value: '4 × 30 kW VFD' },
      { label: 'Fin Type', value: 'Extruded Al' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Process Header In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Sub-Cooled Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Air Exhaust', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Header Drain', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'hx-air-cooled',
  },
  {
    id: 'asset-hx-05',
    tag: 'E-205',
    name: 'Hairpin Double-Pipe Heat Exchanger',
    category: 'exchangers',
    standard: 'ASME Sec VIII Div 1',
    subType: 'Longitudinal Finned Hairpin',
    specs: [
      { label: 'Design Press.', value: '110 bar' },
      { label: 'Counter-Current', value: '100% Pure' },
      { label: 'Duty', value: '3.2 MW' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inner Tube In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Inner Tube Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Annulus Out', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Annulus In', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'hx-hairpin',
  },
  {
    id: 'asset-hx-06',
    tag: 'E-206',
    name: 'Kettle Type Reboiler (TEMA BKU)',
    category: 'exchangers',
    standard: 'TEMA Type BKU / ASME Sec VIII',
    subType: 'Submerged Bundle Reboiler with Vapor Dome',
    specs: [
      { label: 'Boiling Duty', value: '26.4 MW' },
      { label: 'Surge Volume', value: '12.8 m³' },
      { label: 'Vapor Space', value: '55% Diameter' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Tower Bottom Liquid', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Bottoms Product', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Reboiled Vapor Return', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Heating Condensate', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'hx-kettle',
  },
  {
    id: 'asset-hx-07',
    tag: 'E-207',
    name: 'Vertical Thermosiphon Reboiler',
    category: 'exchangers',
    standard: 'TEMA Type BEM Vertical',
    subType: 'Natural Circulation Once-Through',
    specs: [
      { label: 'Circulation Ratio', value: '4.2 : 1' },
      { label: 'Steam Pressure', value: '12.5 bar g' },
      { label: 'Vapor Outlet', value: 'Annular Mist' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Column Liquid', position: 'bottom' },
      { id: 'outlet', type: 'outlet', label: 'Two-Phase Vapor', position: 'top' },
      { id: 'vent', type: 'vent', label: 'Steam Inlet', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Condensate Drain', position: 'left' },
    ],
    color: '#06b6d4',
    symbol: 'hx-thermosiphon',
  },
  {
    id: 'asset-hx-08',
    tag: 'E-208',
    name: 'Spiral Flow Heat Exchanger',
    category: 'exchangers',
    standard: 'ASME Sec VIII Div 1',
    subType: 'Single-Channel Self-Cleaning Spiral',
    specs: [
      { label: 'Sludge Tolerance', value: 'Extreme' },
      { label: 'Flow Velocity', value: '2.1 m/s' },
      { label: 'Duty', value: '6.7 MW' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Media A In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Media A Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Media B Out', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Media B In', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'hx-spiral',
  },
  {
    id: 'asset-hx-09',
    tag: 'E-209',
    name: 'Surface Steam Condenser',
    category: 'exchangers',
    standard: 'HEI Standards / ASME Sec VIII',
    subType: 'Vacuum Shell Turbine Condenser',
    specs: [
      { label: 'Condensing Duty', value: '45.0 MW' },
      { label: 'Vacuum Level', value: '0.08 bar a' },
      { label: 'Hotwell Cap.', value: '8.5 m³' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Turbine Exhaust Steam', position: 'top' },
      { id: 'outlet', type: 'outlet', label: 'Condensate to Hotwell', position: 'bottom' },
      { id: 'vent', type: 'vent', label: 'Cooling Water In', position: 'left' },
      { id: 'drain', type: 'drain', label: 'Cooling Water Out', position: 'right' },
    ],
    color: '#06b6d4',
    symbol: 'hx-condenser',
  },
  {
    id: 'asset-hx-10',
    tag: 'H-210',
    name: 'Direct-Fired Process Furnace (API 560)',
    category: 'exchangers',
    standard: 'API 560 / ISO 13705',
    subType: 'Cabin Type Radiant & Convection Heater',
    specs: [
      { label: 'Heat Absorbed', value: '38.5 MW' },
      { label: 'Thermal Eff.', value: '92.4%' },
      { label: 'Burners', value: '16 Ultra-Low NOx' },
      { label: 'Bridge Wall Temp', value: '890°C' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Cold Feed Charge', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Fired Transfer Line', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Flue Gas Stack', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Fuel Gas Header', position: 'bottom' },
    ],
    color: '#f97316',
    symbol: 'furnace-fired',
  },

  // ----------------------------------------------------
  // 3. COLUMNS, VESSELS & REACTORS (10 items)
  // ----------------------------------------------------
  {
    id: 'asset-col-01',
    tag: 'C-301',
    name: 'process stream Fractionation Distillation Column',
    category: 'columns',
    standard: 'ASME Sec VIII Div 2 / API 510',
    subType: 'Multi-Draw Tray Column (54 Trays)',
    specs: [
      { label: 'Diameter', value: '4.8 m' },
      { label: 'Height (T/T)', value: '48.5 m' },
      { label: 'Trays', value: '54 Valve Trays' },
      { label: 'Side Draws', value: 'Kerosene, Diesel, AGO' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Flash Zone Feed', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Bottoms Stripped Stream', position: 'bottom' },
      { id: 'vent', type: 'vent', label: 'Overhead Vapor Line', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Side-Stream Draw', position: 'right' },
    ],
    color: '#06b6d4',
    symbol: 'column-trayed',
  },
  {
    id: 'asset-col-02',
    tag: 'C-302',
    name: 'Absorption Packed Tower',
    category: 'columns',
    standard: 'ASME Sec VIII Div 1',
    subType: 'Structured Packing Acid Gas Absorber',
    specs: [
      { label: 'Packing Type', value: 'Mellapak 250Y' },
      { label: 'HETP', value: '0.45 m' },
      { label: 'H2S Removal', value: '99.98%' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Sour Gas Feed', position: 'bottom' },
      { id: 'outlet', type: 'outlet', label: 'Rich Solvent Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Sweet Gas Vent', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Lean Solvent In', position: 'left' },
    ],
    color: '#06b6d4',
    symbol: 'column-packed',
  },
  {
    id: 'asset-col-03',
    tag: 'C-303',
    name: 'Side-Stream Stripper Column',
    category: 'columns',
    standard: 'ASME Sec VIII Div 1',
    subType: 'Steam Stripper with Structured Trays',
    specs: [
      { label: 'Trays', value: '8 Bubble-Cap' },
      { label: 'Steam Inject', value: '1.2 t/h' },
      { label: 'Flash Point Adj', value: '+8.5°C' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Column Liquid Feed', position: 'top' },
      { id: 'outlet', type: 'outlet', label: 'Stripped Product Out', position: 'bottom' },
      { id: 'vent', type: 'vent', label: 'Vapor Return to Main Column', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Stripping Steam In', position: 'left' },
    ],
    color: '#06b6d4',
    symbol: 'column-stripper',
  },
  {
    id: 'asset-ves-04',
    tag: 'V-304',
    name: 'Vertical Vapor-Liquid Separator (Reflux Drum)',
    category: 'columns',
    standard: 'ASME Sec VIII Div 1 / API 521',
    subType: 'Vertical Drum with Wire Mesh Demister',
    specs: [
      { label: 'Droplet Cutoff', value: '10 µm' },
      { label: 'Liquid Holdup', value: '5.0 min (NLL)' },
      { label: 'Design Press.', value: '18 bar g' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Condensate Two-Phase In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Liquid Reflux Out', position: 'bottom' },
      { id: 'vent', type: 'vent', label: 'Off-Gas Vent to Flare', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Water Boot Drain', position: 'right' },
    ],
    color: '#06b6d4',
    symbol: 'vessel-vertical',
  },
  {
    id: 'asset-ves-05',
    tag: 'V-305',
    name: 'Horizontal 3-Phase Separator (Oil/Water/Gas)',
    category: 'columns',
    standard: 'API Spec 12J / ASME Sec VIII',
    subType: 'Horizontal Boot & Weir Three-Phase Separator',
    specs: [
      { label: 'Retention Time', value: '15 min (Oil)' },
      { label: 'Internal Weirs', value: 'Double Perforated' },
      { label: 'Gas Velocity', value: '0.85 m/s' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Wellhead Emulsion In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Degassed Oil Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Vapor Header to K-101', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Produced Water Out', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'vessel-horizontal',
  },
  {
    id: 'asset-ves-06',
    tag: 'V-306',
    name: 'High-Pressure Coalescer Filter Vessel',
    category: 'columns',
    standard: 'ASME Sec VIII Div 1',
    subType: 'Micro-Fiber Liquid-Liquid Coalescer',
    specs: [
      { label: 'Effluent Purity', value: '< 10 ppm H2O' },
      { label: 'Filter Cartridges', value: '24 Depth Cartridges' },
      { label: 'Delta P Alarm', value: '1.2 bar' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Wet Hydrocarbon Feed', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Dry Hydrocarbon Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Vent', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Separated Water Drain', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'vessel-coalescer',
  },
  {
    id: 'asset-ves-07',
    tag: 'V-307',
    name: 'Compressor Suction Knock-Out Drum',
    category: 'columns',
    standard: 'API 617 / ASME Sec VIII',
    subType: 'Suction Scrubber with Cyclonic Inlet',
    specs: [
      { label: 'Protection Tag', value: 'K-501 Suction' },
      { label: 'Demister Mat', value: 'Vane Pack SS316L' },
      { label: 'High Level Trip', value: 'SIL-3 Interlock' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Wet Gas Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Dry Gas to Compressor', position: 'top' },
      { id: 'vent', type: 'vent', label: 'PSV Relief Nozzle', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Condensed Slop Drain', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'vessel-vertical',
  },
  {
    id: 'asset-ves-08',
    tag: 'V-308',
    name: 'Flash Surge Drum',
    category: 'columns',
    standard: 'ASME Sec VIII Div 1',
    subType: 'De-pressurizing Flash Vessel',
    specs: [
      { label: 'Flash Delta P', value: '14.5 bar drop' },
      { label: 'Vapor Rate', value: '18,500 Nm³/h' },
      { label: 'Operating Temp', value: '64.0°C' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'High Pressure Feed', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Stabilized Liquid Out', position: 'bottom' },
      { id: 'vent', type: 'vent', label: 'Flashed Offgas Out', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Boot Purge', position: 'right' },
    ],
    color: '#06b6d4',
    symbol: 'vessel-horizontal',
  },
  {
    id: 'asset-react-09',
    tag: 'R-309',
    name: 'Fixed Bed Catalytic Hydrotreater Reactor',
    category: 'columns',
    standard: 'API 934 / ASME Sec VIII Div 2',
    subType: 'Thick-Wall Heavy Wall 2.25Cr-1Mo-V Reactor',
    specs: [
      { label: 'Design Temp', value: '450°C' },
      { label: 'Design Press.', value: '165 bar g' },
      { label: 'Bed Catalyst', value: 'NiMo on Alumina' },
      { label: 'Quench Zones', value: '3 H2 Injections' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Combined Feed + H2', position: 'top' },
      { id: 'outlet', type: 'outlet', label: 'Effluent to HP Separator', position: 'bottom' },
      { id: 'vent', type: 'vent', label: 'Safety Blowdown BDV', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Quench H2 Header', position: 'left' },
    ],
    color: '#06b6d4',
    symbol: 'reactor-catalytic',
  },
  {
    id: 'asset-react-10',
    tag: 'R-310',
    name: 'Fluid Catalytic Cracking Reactor (FCC)',
    category: 'columns',
    standard: 'ASME Sec VIII Div 2',
    subType: 'Riser-Disengager Regenerator System',
    specs: [
      { label: 'Riser Exit Temp', value: '535°C' },
      { label: 'Catalyst Circ.', value: '35 t/min Zeolite' },
      { label: 'Cyclones', value: 'Two-Stage Ballistic' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Hot Regenerated Cat', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Cracked Vapors to Main Col', position: 'top' },
      { id: 'vent', type: 'vent', label: 'Spent Cat to Regen', position: 'bottom' },
      { id: 'drain', type: 'drain', label: 'Feed Oil Atomizing Steam', position: 'right' },
    ],
    color: '#06b6d4',
    symbol: 'reactor-fcc',
  },

  // ----------------------------------------------------
  // 4. VALVES & ACTUATORS (13 items)
  // ----------------------------------------------------
  {
    id: 'asset-valve-01',
    tag: 'HV-401',
    name: 'Manual Gate Isolation Valve',
    category: 'valves',
    standard: 'API 600 / ASME B16.34',
    subType: 'OS&Y Bolted Bonnet Wedge Gate Valve',
    specs: [
      { label: 'Rating', value: 'Class 300 RF' },
      { label: 'Body', value: 'ASTM A216 WCB' },
      { label: 'Trim', value: 'API Trim 8 (Stellite)' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Outlet', position: 'right' },
    ],
    color: '#f59e0b',
    symbol: 'valve-gate',
  },
  {
    id: 'asset-valve-02',
    tag: 'HV-402',
    name: 'Globe Throttling Valve',
    category: 'valves',
    standard: 'BS 1873 / ASME B16.34',
    subType: 'High-Differential Throttling Globe',
    specs: [
      { label: 'Rating', value: 'Class 600 RTJ' },
      { label: 'Plug', value: 'Parabolic Hardened' },
      { label: 'Flow Curve', value: 'Linear' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Outlet', position: 'right' },
    ],
    color: '#f59e0b',
    symbol: 'valve-globe',
  },
  {
    id: 'asset-valve-03',
    tag: 'XV-403',
    name: 'Automated Emergency Shutoff Ball Valve',
    category: 'valves',
    standard: 'API 6D / ISO 14313 (SIL-3)',
    subType: 'Trunnion Mounted Full Bore Ball Valve',
    specs: [
      { label: 'Safety Integrity', value: 'SIL-3 Rated' },
      { label: 'Closure Time', value: '< 2.0 s' },
      { label: 'Fire Safe', value: 'API 607 Certified' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Outlet', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Body Bleed', position: 'top' },
    ],
    color: '#f59e0b',
    symbol: 'valve-ball',
  },
  {
    id: 'asset-valve-04',
    tag: 'XV-404',
    name: 'High-Performance Triple Offset Butterfly Valve',
    category: 'valves',
    standard: 'API 609 Cat B / ASME B16.34',
    subType: 'Bidirectional Zero-Leakage Metal Seated',
    specs: [
      { label: 'Shutoff Class', value: 'FCI 70-2 Class VI' },
      { label: 'Wafer / Lug', value: 'Lugged ASME 150#' },
      { label: 'Torque', value: 'Optimized Low Friction' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Outlet', position: 'right' },
    ],
    color: '#f59e0b',
    symbol: 'valve-butterfly',
  },
  {
    id: 'asset-valve-05',
    tag: 'CV-405',
    name: 'Swing Check Non-Return Valve',
    category: 'valves',
    standard: 'API 594 / ASME B16.34',
    subType: 'Counter-Weighted Swing Check',
    specs: [
      { label: 'Cracking Press.', value: '0.05 bar' },
      { label: 'Non-Slam', value: 'Hydraulic Dashpot' },
      { label: 'Backflow Leak', value: '0 cm³/min' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Upstream Flange', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Downstream Flange', position: 'right' },
    ],
    color: '#f59e0b',
    symbol: 'valve-check',
  },
  {
    id: 'asset-valve-06',
    tag: 'CV-406',
    name: 'Dual-Plate Wafer Check Valve',
    category: 'valves',
    standard: 'API 594 Type B',
    subType: 'Torsion Spring Twin Flapper Check',
    specs: [
      { label: 'Installation', value: 'Horizontal / Vertical' },
      { label: 'Pressure Loss', value: 'Low Delta P' },
      { label: 'Response', value: 'Fast Closure (<0.15s)' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Outlet', position: 'right' },
    ],
    color: '#f59e0b',
    symbol: 'valve-check',
  },
  {
    id: 'asset-valve-07',
    tag: 'PSV-407',
    name: 'Spring-Loaded Pressure Safety Valve (PSV)',
    category: 'valves',
    standard: 'API 526 / API 520 / ASME Sec VIII',
    subType: 'Direct Spring Loaded Safety Relief Valve',
    specs: [
      { label: 'Set Pressure', value: '42.0 bar g' },
      { label: 'Orifice Letter', value: 'Orifice J (830 mm²)' },
      { label: 'Overpressure', value: '10% ASME Relief' },
      { label: 'Fluid', value: 'Vapor / Gas' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Protected Vessel Nozzle', position: 'bottom' },
      { id: 'outlet', type: 'outlet', label: 'Discharge to Flare Header', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Bonnet Vent', position: 'top' },
    ],
    color: '#ef4444',
    symbol: 'valve-psv',
  },
  {
    id: 'asset-valve-08',
    tag: 'PSV-408',
    name: 'Pilot-Operated Relief Valve (PORV)',
    category: 'valves',
    standard: 'API 526 / ASME Sec VIII',
    subType: 'Snap-Action Non-Flowing Pilot Relief',
    specs: [
      { label: 'Backpressure', value: 'Up to 70% Set Press.' },
      { label: 'Set Accuracy', value: '±1.0%' },
      { label: 'High Capacity', value: 'Orifice T (16,774 mm²)' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Process Inlet', position: 'bottom' },
      { id: 'outlet', type: 'outlet', label: 'Atmospheric Discharge', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Sense Line', position: 'left' },
    ],
    color: '#ef4444',
    symbol: 'valve-porv',
  },
  {
    id: 'asset-valve-09',
    tag: 'FV-409',
    name: 'Pneumatic Diaphragm Flow Control Valve (FC)',
    category: 'valves',
    standard: 'ISA 75.01 / IEC 60534',
    subType: 'Air-to-Open Fail-Closed Globe Control Valve',
    specs: [
      { label: 'Actuator', value: 'Diaphragm + Positioner' },
      { label: 'Signal', value: '4-20 mA / HART' },
      { label: 'Trim Characteristic', value: 'Equal Percentage' },
      { label: 'Cv Rating', value: '240 gpm/psi' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Process Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Process Outlet', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Air Signal (IA)', position: 'top' },
    ],
    color: '#f59e0b',
    symbol: 'valve-control',
  },
  {
    id: 'asset-valve-10',
    tag: 'PV-410',
    name: 'Motor-Operated Pressure Control Valve (MOV)',
    category: 'valves',
    standard: 'IEC 60079 Ex d / AWWA C541',
    subType: 'Explosion-Proof Electric Intelligent Actuator',
    specs: [
      { label: 'Power', value: '380V 3-Phase 50Hz' },
      { label: 'Modulating Duty', value: '1,200 starts/hr' },
      { label: 'Fieldbus', value: 'Modbus TCP / Profinet' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Outlet', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Power Conduits', position: 'top' },
    ],
    color: '#f59e0b',
    symbol: 'valve-mov',
  },
  {
    id: 'asset-valve-11',
    tag: 'TV-411',
    name: '3-Way Temperature Diverter Control Valve',
    category: 'valves',
    standard: 'IEC 60534 / ISA 75',
    subType: 'Linear Diverting Plug Control Valve',
    specs: [
      { label: 'Action', value: 'Exchanger Bypass Ratio' },
      { label: 'Stroke', value: '50 mm' },
      { label: 'Response', value: '< 1.5 s step' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Common In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Through Heat Exchanger', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Bypass Line', position: 'bottom' },
      { id: 'vent', type: 'vent', label: 'Pneumatic Actuator', position: 'top' },
    ],
    color: '#f59e0b',
    symbol: 'valve-threeway',
  },
  {
    id: 'asset-valve-12',
    tag: 'BDV-412',
    name: 'Emergency Cryogenic Depressuring Blowdown Valve (BDV)',
    category: 'valves',
    standard: 'API 521 § 5.4 / SIL-3 IEC 61508',
    subType: 'Fail-Open Fast Acting Depressuring Valve',
    specs: [
      { label: 'Action', value: 'Fail-Safe Open (FO)' },
      { label: '15-Min Decay', value: '85.0 -> 0.9 bar a' },
      { label: 'J-T Temp', value: '-52.4°C Design' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Reactor Loop Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Cold Flare Header', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Solenoid Pilot SOV', position: 'top' },
    ],
    color: '#ef4444',
    symbol: 'valve-control',
  },
  {
    id: 'asset-valve-13',
    tag: 'NV-413',
    name: 'High-Precision Needle Metering Valve',
    category: 'valves',
    standard: 'ASME B16.34 Class 2500',
    subType: 'Fine Pitch Regulating Stem Needle Valve',
    specs: [
      { label: 'Rating', value: 'Class 2500 (414 bar)' },
      { label: 'Orifice', value: '3.2 mm' },
      { label: 'Usage', value: 'Instrument Sample Line' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Sample Needle Out', position: 'right' },
    ],
    color: '#f59e0b',
    symbol: 'valve-needle',
  },

  // ----------------------------------------------------
  // 5. COMPRESSORS & TURBINES (8 items)
  // ----------------------------------------------------
  {
    id: 'asset-comp-01',
    tag: 'K-501',
    name: 'Multi-Stage Centrifugal Gas Compressor',
    category: 'compressors',
    standard: 'API 617 8th Ed / ISO 10439',
    subType: 'Horizontally Split Barrel Centrifugal Compressor',
    specs: [
      { label: 'Stages', value: '4 Impellers' },
      { label: 'Shaft Speed', value: '11,200 RPM' },
      { label: 'Inlet Volume', value: '28,500 m³/h' },
      { label: 'Pressure Ratio', value: '4.25 : 1' },
      { label: 'Driver Power', value: '12.5 MW' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction Nozzle', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge Nozzle', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Dry Gas Seal Vent', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Anti-Surge Recycle', position: 'bottom' },
    ],
    color: '#f43f5e',
    symbol: 'comp-centrifugal',
  },
  {
    id: 'asset-comp-02',
    tag: 'K-502',
    name: 'Reciprocating Balanced-Opposed Gas Compressor',
    category: 'compressors',
    standard: 'API 618 5th Ed / ISO 13631',
    subType: '4-Throw 2-Stage Reciprocating Machine',
    specs: [
      { label: 'Discharge Press.', value: '145 bar' },
      { label: 'Rod Load', value: '285 kN' },
      { label: 'Pulsation Damping', value: 'API 618 Design Approach 3' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Stage 1 Suction', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Final Discharge', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Distance Piece Vent', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Condensate Purge', position: 'bottom' },
    ],
    color: '#f43f5e',
    symbol: 'comp-reciprocating',
  },
  {
    id: 'asset-comp-03',
    tag: 'K-503',
    name: 'Twin-Screw Rotary Gas Compressor',
    category: 'compressors',
    standard: 'API 619 / ISO 10440',
    subType: 'Oil-Injected Helical Screw Compressor',
    specs: [
      { label: 'Volume Control', value: 'Slide Valve (10-100%)' },
      { label: 'Discharge Temp', value: '88°C' },
      { label: 'MW Range', value: '2.0 to 45.0 kg/kmol' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Suction Port', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge Port', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Lube Injection', position: 'bottom' },
    ],
    color: '#f43f5e',
    symbol: 'comp-screw',
  },
  {
    id: 'asset-comp-04',
    tag: 'K-504',
    name: 'Multi-Stage Axial Flow Air Compressor',
    category: 'compressors',
    standard: 'API 617 Part 3',
    subType: 'Variable Stator Vane Axial Compressor',
    specs: [
      { label: 'Mass Flow', value: '140 kg/s Air' },
      { label: 'Efficiency', value: '89.2% Isentropic' },
      { label: 'Compression Ratio', value: '16.5 : 1' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Bellmouth Intake', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Diffuser Exit', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Anti-Stall Bleed', position: 'top' },
    ],
    color: '#f43f5e',
    symbol: 'comp-axial',
  },
  {
    id: 'asset-turb-05',
    tag: 'GT-505',
    name: 'Industrial Aeroderivative Gas Turbine Driver',
    category: 'compressors',
    standard: 'API 616 / ISO 3977',
    subType: 'Dual-Shaft Heavy Duty Gas Turbine',
    specs: [
      { label: 'ISO Power Output', value: '32.4 MW' },
      { label: 'Heat Rate', value: '9,250 kJ/kWh' },
      { label: 'Exhaust Temp', value: '495°C' },
      { label: 'Speed', value: '5,400 RPM' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Fuel Gas In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Output Drive Shaft', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Exhaust to HRSG', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Combustor Drain', position: 'bottom' },
    ],
    color: '#f43f5e',
    symbol: 'driver-turbine',
  },
  {
    id: 'asset-turb-06',
    tag: 'ST-506',
    name: 'Multi-Stage Extraction Steam Turbine Drive',
    category: 'compressors',
    standard: 'API 612 7th Ed / ISO 10437',
    subType: 'Condensing & Controlled Extraction Turbine',
    specs: [
      { label: 'Inlet Steam', value: '64 bar / 480°C' },
      { label: 'Extraction', value: '16 bar MP Steam' },
      { label: 'Shaft Power', value: '18.2 MW' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'HP Steam In', position: 'top' },
      { id: 'outlet', type: 'outlet', label: 'Exhaust to Condenser', position: 'bottom' },
      { id: 'vent', type: 'vent', label: 'MP Extraction Header', position: 'left' },
      { id: 'drain', type: 'drain', label: 'Drive Flange', position: 'right' },
    ],
    color: '#f43f5e',
    symbol: 'driver-steamturbine',
  },
  {
    id: 'asset-comp-07',
    tag: 'TE-507',
    name: 'Cryogenic Turbo-Expander Generator Package',
    category: 'compressors',
    standard: 'API 617 Part 4',
    subType: 'Integral Gear Expander-Compressor (Compander)',
    specs: [
      { label: 'Refrigeration', value: '-85.0°C Chilling' },
      { label: 'Work Recovery', value: '2,400 kW' },
      { label: 'Magnetic Bearings', value: 'Active AMB' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'High Pressure Gas In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Cryogenic Chilled Liquid', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Brake Compressor In', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Brake Compressor Out', position: 'bottom' },
    ],
    color: '#f43f5e',
    symbol: 'comp-expander',
  },
  {
    id: 'asset-comp-08',
    tag: 'B-508',
    name: 'Centrifugal Forced Draft Blower',
    category: 'compressors',
    standard: 'API 673 2nd Ed / ISO 13349',
    subType: 'Heavy Industrial Single-Inlet Fan',
    specs: [
      { label: 'Air Flow', value: '65,000 Nm³/h' },
      { label: 'Static Head', value: '8.5 kPa' },
      { label: 'Combustion Target', value: 'H-210 Fired Heater' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Air Intake Silencer', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Burner Plenum Duct', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Inlet Vane Damper', position: 'top' },
    ],
    color: '#f43f5e',
    symbol: 'comp-blower',
  },

  // ----------------------------------------------------
  // 6. TANKS, STORAGE & IN-LINE INSTRUMENTS (8 items)
  // ----------------------------------------------------
  {
    id: 'asset-tk-01',
    tag: 'TK-601',
    name: 'Cone Roof Atmospheric Storage Tank',
    category: 'tanks',
    standard: 'API 650 12th Ed / ISO 28300',
    subType: 'Fixed Cone Roof Atmospheric Oil Storage',
    specs: [
      { label: 'Capacity', value: '25,000 m³' },
      { label: 'Diameter', value: '42.0 m' },
      { label: 'Height', value: '18.5 m' },
      { label: 'Blanket Gas', value: 'Low-Pressure N2' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Fill Nozzle', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Pump Suction Nozzle', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Breather Valve PVRV', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Water Draw Sump', position: 'bottom' },
    ],
    color: '#3b82f6',
    symbol: 'tank-atmospheric',
  },
  {
    id: 'asset-tk-02',
    tag: 'TK-602',
    name: 'External Floating Roof process stream Storage Tank',
    category: 'tanks',
    standard: 'API 650 Annex C',
    subType: 'Double-Deck Pontoon Floating Roof Tank',
    specs: [
      { label: 'Capacity', value: '80,000 m³' },
      { label: 'Diameter', value: '76.0 m' },
      { label: 'Secondary Seal', value: 'Rim Wiper Vapor Barrier' },
      { label: 'VOC Loss Red.', value: '98.5%' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'process stream Discharge In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Booster Pump Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Roof Drain Hose', position: 'bottom' },
      { id: 'drain', type: 'drain', label: 'Mixer Port', position: 'top' },
    ],
    color: '#3b82f6',
    symbol: 'tank-floating',
  },
  {
    id: 'asset-tk-03',
    tag: 'TK-603',
    name: 'Horton Spherical Pressure Storage Sphere (LPG)',
    category: 'tanks',
    standard: 'ASME Sec VIII Div 1 / API 2510',
    subType: 'Pressurized LPG / NGL Horton Sphere',
    specs: [
      { label: 'Design Press.', value: '18.5 bar g' },
      { label: 'Volume', value: '5,000 m³' },
      { label: 'Water Deluge', value: 'NFPA 15 High Velocity' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'LPG In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'LPG Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Dual Safety PSV', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Bottom Emergency Block', position: 'bottom' },
    ],
    color: '#3b82f6',
    symbol: 'tank-sphere',
  },
  {
    id: 'asset-tk-04',
    tag: 'TK-604',
    name: 'Horizontal Pressurized Bullet Storage Tank',
    category: 'tanks',
    standard: 'ASME Sec VIII Div 1',
    subType: 'Pressurized Propane/Butane Bullet',
    specs: [
      { label: 'Capacity', value: '450 m³' },
      { label: 'Length', value: '32.0 m' },
      { label: 'Fireproofing', value: 'Intumescent Coating' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Discharge', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Relief Nozzle', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Bottom Sump', position: 'bottom' },
    ],
    color: '#3b82f6',
    symbol: 'tank-bullet',
  },
  {
    id: 'asset-inline-05',
    tag: 'FE-701',
    name: 'Orifice Meter Flange Metering Run',
    category: 'inline',
    standard: 'ISO 5167-2 / AGA 3',
    subType: 'Square-Edged Concentric Orifice Run',
    specs: [
      { label: 'Beta Ratio', value: '0.6200' },
      { label: 'Flange Taps', value: '1" NPT Pairs' },
      { label: 'Turndown', value: '4 : 1' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Upstream Straight Run', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Downstream Run', position: 'right' },
      { id: 'vent', type: 'vent', label: 'High Press. Tap (HP)', position: 'top' },
      { id: 'drain', type: 'drain', label: 'Low Press. Tap (LP)', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'inline-orifice',
  },
  {
    id: 'asset-inline-06',
    tag: 'FE-702',
    name: 'Venturi Tube Differential Flow Element',
    category: 'inline',
    standard: 'ISO 5167-4 / ASME MFC-3M',
    subType: 'Machined Convergent-Divergent Venturi',
    specs: [
      { label: 'Head Loss', value: '< 8% of Delta P' },
      { label: 'Throat Ratio', value: '0.55' },
      { label: 'Durability', value: 'Zero Maintenance' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Upstream Flange', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Diffuser Exit', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Throat Tap', position: 'top' },
    ],
    color: '#06b6d4',
    symbol: 'inline-venturi',
  },
  {
    id: 'asset-inline-07',
    tag: 'STR-703',
    name: 'Inline Y-Type High Pressure Strainer',
    category: 'inline',
    standard: 'ASME B16.34 Class 600',
    subType: 'Stainless Steel Mesh Basket Strainer',
    specs: [
      { label: 'Mesh Size', value: '40 Mesh (400 µm)' },
      { label: 'Blow-off Valve', value: '3/4" Ball Valve' },
      { label: 'Body', value: 'Forged A105N' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Inlet', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Outlet', position: 'right' },
      { id: 'drain', type: 'drain', label: 'Blow-Off Cleanout', position: 'bottom' },
    ],
    color: '#06b6d4',
    symbol: 'inline-strainer',
  },
  {
    id: 'asset-inline-08',
    tag: 'MX-704',
    name: 'Helical Inline Static Fluid Mixer',
    category: 'inline',
    standard: 'API 8.2 / ASTM D4057',
    subType: 'Fixed Helical Element Custody Sampling Mixer',
    specs: [
      { label: 'Elements', value: '6 Twist Elements (SS316)' },
      { label: 'CoV Mixing', value: '< 0.05 Coefficient' },
      { label: 'Reynolds', value: '> 10,000 Turbulent' },
    ],
    ports: [
      { id: 'inlet', type: 'inlet', label: 'Main Stream In', position: 'left' },
      { id: 'outlet', type: 'outlet', label: 'Mixed Stream Out', position: 'right' },
      { id: 'vent', type: 'vent', label: 'Additive Quill In', position: 'top' },
    ],
    color: '#06b6d4',
    symbol: 'inline-mixer',
  },
];
